### ISSUE TITLE
偶然出现播放卡8-10秒的问题

### ISSUE THREAD

**Issue by Dreamskya** [masterwok/libvlc-android-sdk#2]
大佬，您好，反反复复退出，又进行播放，进来后视频播放会卡8-10秒，然后才能恢复流畅预览？是什么原因呢？它不是每次都会卡8-10秒，是偶然出现的，出现概率也挺大。不知道是什么原因呢？

**Comment by masterwok** [comment]
Hi Dreamskya, unfortunately I'm not sure what would cause this issue. I only compiled the library to bring it into another project. If you think the issue exists within the library you could try rebuilding the library with the latest sources by following the directions in this repositories readme. Best of luck.
